[versions]
kotlin = "2.2.20"
spring-boot = "3.5.6"
spring-dependency-management = "1.1.7"
spotless = "8.0.0"
kotest-plugin = "6.0.3"
kotest = "6.0.3"
spring-modulith = "1.4.3"
ktlint = "1.4.1"
kotlin-logging = "7.0.13"

[libraries]
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-data-jdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
flyway-core = { module = "org.flywaydb:flyway-core" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
spring-modulith-starter-core = { module = "org.springframework.modulith:spring-modulith-starter-core" }
spring-modulith-starter-jdbc = { module = "org.springframework.modulith:spring-modulith-starter-jdbc" }
h2 = { module = "com.h2database:h2" }
spring-modulith-actuator = { module = "org.springframework.modulith:spring-modulith-actuator" }
spring-modulith-observability = { module = "org.springframework.modulith:spring-modulith-observability" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
spring-modulith-starter-test = { module = "org.springframework.modulith:spring-modulith-starter-test" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-extensions-spring = { module = "io.kotest:kotest-extensions-spring", version.ref = "kotest" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotest = { id = "io.kotest", version.ref = "kotest-plugin" }
